database:
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=root; Password=password"
    
# Replace 127.0.0.1 with your database IP
# The port (the section after the :) goes in the port
# Database is your database name
# User is the database user
# Password is the users password
